title: "Reza Kahkeshani"
description: "Personal website and blog of Reza Kahkeshani"
baseurl: ""
url: "https://rezakahkeshani.ir"
markdown: kramdown
author: 
  name: "Reza Kahkeshani"
  email: "kahkeshanireza@kashanu.ac.ir"
plugins:
  - jekyll-sitemap
  - jemoji

jekyll_admin:
  hidden_links:
    - staticfiles
    - datafiles
    - configuration
  homepage: "posts"

exclude:
  - .all-contributorsrc
  - .editorconfig
  - .github
  - .gitignore
  - .jekyll-cache
  - .pre-commit-config.yaml
  - CODEOWNERS
  - codespell.txt
  - Gemfile
  - Gemfile.lock
  - vendor
  - server
  - super-linter.report
  