title: "Reza Kahkeshani"
description: "Personal website and blog of Reza Kahkeshani"
baseurl: ""
url: "https://rezakahkeshani.ir"
author: 
  name: "Reza Kahkeshani"
  email: "kahkeshanireza@kashanu.ac.ir"
# remote_theme: mmistakes/minimal-mistakes@3.3.0
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate: 5
paginate_path: "/page:num/"
